# Generated by Django 4.0.6 on 2022-09-19 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
